<a href="https://colab.research.google.com/github/Berchie-Sam/Machine-Learning/blob/main/Categorical_Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Categorical Data => qualitative data that can be grouped into categories instead of measured numerically and distict from each other.

In [1]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/cars.csv', delimiter=';')

In [5]:
df = dataset.head(10)
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.,12.0,70,US
2,Buick Skylark 320,15.0,8,350.0,165.0,3693.,11.5,70,US
3,Plymouth Satellite,18.0,8,318.0,150.0,3436.,11.0,70,US
4,AMC Rebel SST,16.0,8,304.0,150.0,3433.,12.0,70,US
5,Ford Torino,17.0,8,302.0,140.0,3449.,10.5,70,US
6,Ford Galaxie 500,15.0,8,429.0,198.0,4341.,10.0,70,US
7,Chevrolet Impala,14.0,8,454.0,220.0,4354.,9.0,70,US
8,Plymouth Fury iii,14.0,8,440.0,215.0,4312.,8.5,70,US
9,Pontiac Catalina,14.0,8,455.0,225.0,4425.,10.0,70,US

In [6]:
df = dataset.tail(10)
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
397,Chrysler Lebaron Medallion,26.0,4,156.0,92.00,2585.,14.5,82,US
398,Ford Grenada l,22.0,6,232.0,112.0,2835,14.7,82,US
399,Toyota Celica GT,32.0,4,144.0,96.00,2665.,13.9,82,Japan
400,Dodge Charger 2.2,36.0,4,135.0,84.00,2370.,13.0,82,US
401,Chevrolet Camaro,27.0,4,151.0,90.00,2950.,17.3,82,US
402,Ford Mustang GL,27.0,4,140.0,86.00,2790.,15.6,82,US
403,Volkswagen Pickup,44.0,4,97.00,52.00,2130.,24.6,82,Europe
404,Dodge Rampage,32.0,4,135.0,84.00,2295.,11.6,82,US
405,Ford Ranger,28.0,4,120.0,79.00,2625.,18.6,82,US
406,Chevy S-10,31.0,4,119.0,82.00,2720.,19.4,82,US

Origin is categorical

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
# Converting the dataframe to numpy array
df = df.iloc[:,:].values

In [9]:
df

array([['Chrysler Lebaron Medallion', '26.0', '4', '156.0', '92.00',
        '2585.', '14.5', '82', 'US'],
       ['Ford Grenada l', '22.0', '6', '232.0', '112.0', '2835', '14.7',
        '82', 'US'],
       ['Toyota Celica GT', '32.0', '4', '144.0', '96.00', '2665.',
        '13.9', '82', 'Japan'],
       ['Dodge Charger 2.2', '36.0', '4', '135.0', '84.00', '2370.',
        '13.0', '82', 'US'],
       ['Chevrolet Camaro', '27.0', '4', '151.0', '90.00', '2950.',
        '17.3', '82', 'US'],
       ['Ford Mustang GL', '27.0', '4', '140.0', '86.00', '2790.',
        '15.6', '82', 'US'],
       ['Volkswagen Pickup', '44.0', '4', '97.00', '52.00', '2130.',
        '24.6', '82', 'Europe'],
       ['Dodge Rampage', '32.0', '4', '135.0', '84.00', '2295.', '11.6',
        '82', 'US'],
       ['Ford Ranger', '28.0', '4', '120.0', '79.00', '2625.', '18.6',
        '82', 'US'],
       ['Chevy S-10', '31.0', '4', '119.0', '82.00', '2720.', '19.4',
        '82', 'US']], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
country = LabelEncoder()

In [14]:
df[:,8] = country.fit_transform(df[:,8])

In [15]:
df

array([['Chrysler Lebaron Medallion', '26.0', '4', '156.0', '92.00',
        '2585.', '14.5', '82', 2],
       ['Ford Grenada l', '22.0', '6', '232.0', '112.0', '2835', '14.7',
        '82', 2],
       ['Toyota Celica GT', '32.0', '4', '144.0', '96.00', '2665.',
        '13.9', '82', 1],
       ['Dodge Charger 2.2', '36.0', '4', '135.0', '84.00', '2370.',
        '13.0', '82', 2],
       ['Chevrolet Camaro', '27.0', '4', '151.0', '90.00', '2950.',
        '17.3', '82', 2],
       ['Ford Mustang GL', '27.0', '4', '140.0', '86.00', '2790.',
        '15.6', '82', 2],
       ['Volkswagen Pickup', '44.0', '4', '97.00', '52.00', '2130.',
        '24.6', '82', 0],
       ['Dodge Rampage', '32.0', '4', '135.0', '84.00', '2295.', '11.6',
        '82', 2],
       ['Ford Ranger', '28.0', '4', '120.0', '79.00', '2625.', '18.6',
        '82', 2],
       ['Chevy S-10', '31.0', '4', '119.0', '82.00', '2720.', '19.4',
        '82', 2]], dtype=object)

In [16]:
# One hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [20]:
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [8])], remainder = 'passthrough')

In [21]:
y = ct.fit_transform(df)

In [23]:
y=pd.DataFrame(y)
y

,0,1,2,3,4,5,6,7,8,9,10
0,0.0,0.0,1.0,Chrysler Lebaron Medallion,26.0,4,156.0,92.00,2585.,14.5,82
1,0.0,0.0,1.0,Ford Grenada l,22.0,6,232.0,112.0,2835,14.7,82
2,0.0,1.0,0.0,Toyota Celica GT,32.0,4,144.0,96.00,2665.,13.9,82
3,0.0,0.0,1.0,Dodge Charger 2.2,36.0,4,135.0,84.00,2370.,13.0,82
4,0.0,0.0,1.0,Chevrolet Camaro,27.0,4,151.0,90.00,2950.,17.3,82
5,0.0,0.0,1.0,Ford Mustang GL,27.0,4,140.0,86.00,2790.,15.6,82
6,1.0,0.0,0.0,Volkswagen Pickup,44.0,4,97.00,52.00,2130.,24.6,82
7,0.0,0.0,1.0,Dodge Rampage,32.0,4,135.0,84.00,2295.,11.6,82
8,0.0,0.0,1.0,Ford Ranger,28.0,4,120.0,79.00,2625.,18.6,82
9,0.0,0.0,1.0,Chevy S-10,31.0,4,119.0,82.00,2720.,19.4,82